In [3]:
import pandas as pd
import numpy as np

In [4]:
!pip install openpyxl

     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     ----------- ---------------------------- 71.7/250.0 kB ? eta -:--:--
     ----------- ---------------------------- 71.7/250.0 kB ? eta -:--:--
     ----------- ---------------------------- 71.7/250.0 kB ? eta -:--:--
     ----------- ---------------------------- 71.7/250.0 kB ? eta -:--:--
     ----------- ---------------------------- 71.7/250.0 kB ? eta -:--:--
     ----------------- ------------------ 122.9/250.0 kB 479.3 kB/s eta 0:00:01
     ----------------- ------------------ 122.9/250.0 kB 479.3 kB/s eta 0:00:01
     ----------------- ------------------ 122.9/250.0 kB 479.3 kB/s eta 0:00:01
     ----------------- --

In [5]:
df = pd.read_excel('homeprices.xlsx')

In [6]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [8]:
from sklearn.linear_model import LinearRegression
le = LinearRegression()
le.fit(df[['area']],df[['price']])

LinearRegression()

In [9]:
le.coef_

array([[135.78767123]])

In [10]:
le.intercept_

array([180616.43835616])

In [15]:
le.predict([[5000]])

C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[859554.79452055]])

In [26]:
import pickle

In [27]:
with open('model_pickle','wb') as file:
    pickle.dump(le,file)


In [29]:
import joblib as jbl
jbl.dump(le,'myjoblib_model')

['myjoblib_model']